# Generated by Django 4.2.2 on 2023-06-21 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("F", "fundacja"), ("OP", "organizacja pozarządowa"), ("ZL", "zbiórka lokalna")],
                        default="F",
                        max_length=2,
                    ),
                ),
                ("categories", models.ManyToManyField(to="home.category")),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("city", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=6)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time", models.TimeField()),
                ("pick_up_comment", models.TextField(blank=True)),
                ("categories", models.ManyToManyField(to="home.category")),
                ("institution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="home.institution")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
