# Generated by Django 4.2.2 on 2023-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
